/*
 * This source file is subject to the license that is bundled with this package in the file LICENSE.
 */
package com.techelevator.services.yelpservicev3.client;

import com.techelevator.services.yelpservicev3.jsonparser.JSONParser;
import com.techelevator.services.yelpservicev3.parser.Parser;

/**
 * All responses include
 * <p>
 * <ul>
 * <li>The original JSON response</li>
 * <li>A DTO that is generated by default by the <code>JSONParser</code> class</li>
 * </ul>
 */
public class Response {
    protected final String jsonResponse;
    protected Parser parser;

    public Response(String jsonResponse) {
        this.jsonResponse = jsonResponse;
        parser = new JSONParser();
    }

    public void useParser(Parser customParser) {
        parser = customParser;
    }

    public String originalResponse() {
        return jsonResponse;
    }
}
